version: '3'
services:
  httpd:
    build: ./httpd
    ports:
      - 8888:80
        #volumes:
        #- ./httpd/htdocs/:/usr/local/apache2/htdocs
    depends_on:
      - sta
  sta:
    image: 52north/sensorweb-server-sta:latest
    # build: https://github.com/52North/sensorweb-server-sta.git#develop
    ports:
      - 8080:8081
      - 1883:1883
      - 8883:8883
    volumes:
      - ./sta/application.yml:/app/application.yml
    environment:
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_N52: TRACE
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/sta
      SPING_JPA_PROPERTIES_HIBERNATE_HBM2DDL: update
      MQTT_BROKER_PLAINTCP_ENABLED: "true"
      MQTT_BROKER_WEBSOCKET_ENABLED: "true"
      MQTT_BROKER_PERSISTENCE_ENABLED: "false"
      SERVER_ROOTURL: http://localhost:8080/sta/
      SERVER_SERVLET_CONTEXT_PATH: /sta
      SERVER_FEATURE_UPDATEFOI: "false"
      SERVER_FEATURE_MQTTPUBLISHTOPICS: Observations
      SERVER_FEATURE_VARIABLEENCODINGTYPE: "false"
      SERVER_FEATURE_ISMOBILE: "false"
    restart: on-failure:10
    depends_on:
    - database

  database:
    image: mdillon/postgis
    restart: on-failure
    environment:
      - POSTGRES_DB=sta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis

    # For debug/show purposes!
    ports:
      - 5432:5432


